### ISSUE TITLE
`xarray` indexing error in `linear_hydrodynamics`

### ISSUE THREAD

**Issue by michaelcdevin** [SNL-WaterPower/WecOptTool#126]
When running `from_bem` where `friction` is set to a float (e.g. `friction = 100.`), I receive the following error:

```
Traceback (most recent call last):
  File "C:\Users\mcdevin\Miniconda3\envs\wecopttool\lib\site-packages\xarray\core\variable.py", line 130, in as_variable
    obj = Variable(*obj)
  File "C:\Users\mcdevin\Miniconda3\envs\wecopttool\lib\site-packages\xarray\core\variable.py", line 320, in __init__
    self._dims = self._parse_dimensions(dims)
  File "C:\Users\mcdevin\Miniconda3\envs\wecopttool\lib\site-packages\xarray\core\variable.py", line 580, in _parse_dimensions
    raise ValueError(
ValueError: dimensions ('radiating_dof', 'influenced_dof') must have the same length as the number of data dimensions, ndim=0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\code\WecOptTool\wecopttool\scratch1.py", line 128, in <module>
    wec = wot.WEC.from_bem(hydro_data_file_name,
  File "c:\code\wecopttool\wecopttool\core.py", line 330, in from_bem
    hydro_data = linear_hydrodynamics(
  File "c:\code\wecopttool\wecopttool\core.py", line 2002, in linear_hydrodynamics
    hydro_data[name] = (dims, data)
  File "C:\Users\mcdevin\Miniconda3\envs\wecopttool\lib\site-packages\xarray\core\dataset.py", line 1463, in __setitem__
    self.update({key: value})
  File "C:\Users\mcdevin\Miniconda3\envs\wecopttool\lib\site-packages\xarray\core\dataset.py", line 4697, in update
    merge_result = dataset_update_method(self, other)
  File "C:\Users\mcdevin\Miniconda3\envs\wecopttool\lib\site-packages\xarray\core\merge.py", line 1102, in dataset_update_method
    return merge_core(
  File "C:\Users\mcdevin\Miniconda3\envs\wecopttool\lib\site-packages\xarray\core\merge.py", line 755, in merge_core
    collected = collect_variables_and_indexes(aligned, indexes=indexes)
  File "C:\Users\mcdevin\Miniconda3\envs\wecopttool\lib\site-packages\xarray\core\merge.py", line 365, in collect_variables_and_indexes
    variable = as_variable(variable, name=name)
  File "C:\Users\mcdevin\Miniconda3\envs\wecopttool\lib\site-packages\xarray\core\variable.py", line 133, in as_variable
    raise error.__class__(
ValueError: Could not convert tuple of form (dims, data[, attrs, encoding]): (['radiating_dof', 'influenced_dof'], 160.3) to Variable.
```

Changing `friction` to be defined as a 2D `np.ndarray` (e.g. `friction = np.array([[100.]])`) resolves the issue, but this isn't intuitive to users.

**Comment by cmichelenstrofer** [comment]
completed/fixed in v2.0
